#!/bin/bash
#
#---------------------------------------------
#       Author: Maxim Ivchenko
#       Date: 27/08/2012
#       Run: ishere proc_name
#       Description: проверка наличия процесса
#       при использовании hearbeat
#---------------------------------------------- 


STATUS_HEARTBET=`cl_status rscstatus`
STATUS_APP=`pgrep $1 | wc -l`

if [ "${STATUS_HEARTBET}" = "all" -a ${STATUS_APP} -eq 0 ]; then
        echo 0                
else   
        echo 1                
fi
