#!/bin/bash

# Auth to MySQL
auth_file="/etc/zabbix/plugins/mysql.conf"

if [ -e ${auth_file} ]; then
        . ${auth_file}
else
        echo "${auth_file} doen't exist"
        exit 1
fi

mysqladmin -u${USERNAME} -p${PASSWORD} -h ${HOST} status|cut -f4 -d":"|cut -f1 -d"S"|sed "s/ //"
